name: vivaldi
version: 7.8.3925.64
summary: Vivaldi Browser - Feature-packed web browser
description: |
    The web browser for techies and people who need a browser that helps them get things done.
    The user interface is fully customizable, including keyboard shortcuts, mouse gestures, and programmable macros.
confinement: strict
license: Proprietary
type: app
website: https://vivaldi.com
grade: stable
base: core24
icon: vivaldi_icon.png
compression: lzo
adopt-info: vivaldi

platforms:
  amd64:
  arm64:

apps:
  vivaldi-stable:
    extensions: [gnome]
    command-chain:
    - bin/gpu-2404-wrapper
    command: bin/vivaldi.launcher
    common-id: com.vivaldi.Vivaldi
    desktop: usr/share/applications/vivaldi-stable.desktop
    plugs:
      - audio-playback
      - audio-record
      - bluez
      - browser-sandbox
      - camera
      - cups
      - desktop
      - desktop-legacy
      - dot-local-share-applications
      - dot-local-share-icons
      - hardware-observe
      - home
      - joystick
      - mount-observe
      - network
      - network-bind
      - network-manager
      - opengl
      - password-manager-service
      - raw-usb
      - removable-media
      - screen-inhibit-control
      - shmem
      - system-packages-doc
      - u2f-devices
      - upower-observe
      - unity7
      - wayland
      - x11
      - gtk-3-themes
      - icon-themes
      - sound-themes
    slots:
      - mpris

plugs:
  browser-sandbox:
    interface: browser-support
    allow-sandbox: true
  shmem:
    interface: shared-memory
    private: true
  chromium-ffmpeg-120726:
    interface: content
    target: $SNAP
    default-provider: chromium-ffmpeg
  gtk-3-themes:
    interface: content
    target: $SNAP/share/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/share/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/share/sounds
    default-provider: gtk-common-themes
  dot-local-share-applications:
    interface: personal-files
    write:
      - $HOME/.local/share/applications
  dot-local-share-icons:
    interface: personal-files
    write:
      - $HOME/.local/share/icons

slots:
  mpris:
    interface: mpris
    name: vivaldi

parts:
  vivaldi-stable:
    plugin: dump
    after:
      - launcher
    source: https://downloads.vivaldi.com/stable/vivaldi-stable-$SNAPCRAFT_PROJECT_VERSION-$CRAFT_ARCH_BUILD_FOR-binsrc.tar.gz
    source-type: tar
    stage-packages:
      - libatk1.0-0
      - libatspi2.0-0
      - libcairo2
      - libcups2
      - libdrm2
      - libgbm1
      - libnspr4
      - libu2f-udev
      - libvulkan1
      - libx11-6
      - libxcb1
      - libxcomposite1
      - libxdamage1
      - libxext6
      - libxfixes3
      - libxkbcommon0
      - libxrandr2
      - wget
      - libgl1
    override-build: |
      snapcraftctl build
      chmod 755 $CRAFT_PART_INSTALL/opt/vivaldi/vivaldi-sandbox
      # These will cause linkage to the gnome-platform supplied qt5 which is ill-advised
      # as it breaks theme support (and thus dark mode) on plasma desktops where qt is selected
      # for ui backend.
      rm -f "$CRAFT_PART_INSTALL/opt/vivaldi/libqt5_shim.so" \
            "$CRAFT_PART_INSTALL/opt/vivaldi/libqt6_shim.so"
    parse-info: [usr/share/appdata/vivaldi.appdata.xml]

  # Copied from Chromium's snapcraft.yaml - patches xdg-icon-resource
  # to place the icons in a different location than dictated by XDG_DATA_HOME.
  # Fixes VB-112129 - PWA Icons not installed in correct location.
  xdg-icon-resource:
    plugin: nil
    stage-packages: [xdg-utils]
    stage: [usr/bin/xdg-icon-resource]
    override-prime: |
      set -eu
      sed -i '/^xdg_user_dir="$XDG_DATA_HOME"$/s|".*"|$SNAP_REAL_HOME/.local/share/|' \
        "$CRAFT_STAGE/usr/bin/xdg-icon-resource"
      craftctl default

  # fix potential issues with libs not supporting gpu accel
  gpu-2404:
    after: [vivaldi-stable]
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
      # Workaround for https://bugs.launchpad.net/snapd/+bug/2055273
      mkdir -p "${CRAFT_PRIME}/gpu-2404"
    prime:
    - bin/gpu-2404-wrapper

  launcher:
    plugin: dump
    source: launcher
    organize:
      '*': bin/
