name: vivaldi
version: 7.1.3570.39
summary: Vivaldi Browser - Feature-packed web browser
description: |
    The web browser for techies and people who need a browser that helps them get things done.
    The user interface is fully customizable, including keyboard shortcuts, mouse gestures, and programmable macros.
confinement: strict
license: Proprietary
type: app
website: https://vivaldi.com
grade: stable
base: core22
icon: vivaldi_icon.png
compression: lzo
adopt-info: vivaldi

architectures:
- build-on: amd64
  build-for: amd64
- build-on: amd64
  build-for: arm64
- build-on: amd64
  build-for: armhf

apps:
  vivaldi-stable:
    extensions: [gnome]
    command: bin/vivaldi.launcher
    common-id: com.vivaldi.Vivaldi
    desktop: usr/share/applications/vivaldi-stable.desktop
    plugs:
      - audio-playback
      - audio-record
      - bluez
      - browser-sandbox
      - camera
      - cups
      - desktop
      - desktop-legacy
      - dot-local-share-applications
      - dot-local-share-icons
      - hardware-observe
      - home
      - joystick
      - mount-observe
      - mpris
      - network
      - network-bind
      - network-manager
      - opengl
      - password-manager-service
      - raw-usb
      - removable-media
      - screen-inhibit-control
      - shmem
      - system-packages-doc
      - u2f-devices
      - upower-observe
      - unity7
      - wayland
      - x11

plugs:
  browser-sandbox:
    interface: browser-support
    allow-sandbox: true
  shmem:
    interface: shared-memory
    private: true
  chromium-ffmpeg-118887:
    interface: content
    target: $SNAP
    default-provider: chromium-ffmpeg
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  dot-local-share-applications:
    interface: personal-files
    write:
      - $HOME/.local/share/applications
  dot-local-share-icons:
    interface: personal-files
    write:
      - $HOME/.local/share/icons

parts:
  vivaldi-stable:
    plugin: dump
    after:
      - launcher
    source: https://downloads.vivaldi.com/stable/vivaldi-stable-$SNAPCRAFT_PROJECT_VERSION-$CRAFT_ARCH_BUILD_FOR-binsrc.tar.gz
    source-type: tar
    stage-packages:
      - libsecret-1-0
      - libatk1.0-0
      - libatspi2.0-0
      - libcairo2
      - libcups2
      - libcurl3-gnutls
      - libdbus-1-3
      - libdrm2
      - libexpat1
      - libgbm1
      - libgtk-3-0
      - libnspr4
      - libnss3
      - libpango-1.0-0
      - libu2f-udev
      - libvulkan1
      - libx11-6
      - libxcb1
      - libxcomposite1
      - libxdamage1
      - libxext6
      - libxfixes3
      - libxkbcommon0
      - libxrandr2
      - wget
      - xdg-utils
      - libasound2
      - libgl1
    override-build: |
      snapcraftctl build
      chmod 755 $CRAFT_PART_INSTALL/opt/vivaldi/vivaldi-sandbox
    parse-info: [usr/share/appdata/vivaldi.appdata.xml]

  # Copied from Chromium's snapcraft.yaml - patches xdg-icon-resource
  # to place the icons in a different location than dictated by XDG_DATA_HOME.
  # Fixes VB-112129 - PWA Icons not installed in correct location.
  xdg-icon-resource:
    plugin: nil
    stage-packages: [xdg-utils]
    stage: [usr/bin/xdg-icon-resource]
    override-prime: |
      find / -path '*/usr/bin/xdg-icon-resource' -print -exec sed -i '/^xdg_user_dir="$XDG_DATA_HOME"$/s|".*"|$SNAP_REAL_HOME/.local/share/|' {} +
      craftctl default

  launcher:
    plugin: dump
    source: launcher
    organize:
      '*': bin/
